- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/styles.scss
Here a proposition for the sidenav design
> Sidenav design

- CONTRIBUTING.md
- README.md
- package.json
- yarn.lock
- Update README.md to be more descriptive. 
- Add CONTRIBUTING.md along the same guidelines as RxJs CONTRIBUTING.md
- Add commitizen, cz-conventional-changelog to dev dependencies
- Add commizen config to package.json to reference cz-conventional-changelog
- Add commit script to package.json to run commitizen as is used by the RxJs repo
No breaking changes. Assists in closing https://github.com/ReactiveX/rxjs-docs/issues/19
> docs(README.md, CONTRIBUTING.md): Update and Add respectively

- package.json
- tslint.json
- Added basic tooling configuration for linting using prettier, tslint.
- Added precommit to run lint on staged files
Close #45
> chore(tooling): Add prettier, lint-staged and precommit hook for tooling

- src/operator-docs/combination/concatAll.ts
Fixes: https://github.com/ReactiveX/rxjs-docs/issues/64
> docs: Adding documentation for concatAll operator.

- README.md
Remove wrong indentation for code block in Committing section.
> docs(README.md): fix code block formatting

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/companies/companies.component.ts
- src/app/companies/companies.module.ts
- src/app/operators/components/operator/operator.component.ts
- src/app/operators/operators.module.ts
- src/app/rxjs/rxjs.module.ts
- src/app/shared.module.ts
- src/app/team/team.module.ts
- src/app/toolbar/toolbar.component.spec.ts
- src/app/toolbar/toolbar.component.ts
- src/app/toolbar/toolbar.module.ts
- src/operator-docs/combination/combineLatest.ts
- src/operator-docs/combination/concatAll.ts
Change double to single quotes to match current tslint settings.
> refactor: change double to single quotes

- src/operator-docs/transformation/groupBy.ts
> docs(groupBy): Add documentation for groupBy operator

- src/operator-docs/filtering/debounceTime.ts
> docs(89): brings content for documentation of debounceTime-operator

- src/operator-docs/combination/mergeAll.ts
Closes: https://github.com/ReactiveX/rxjs-docs/issues/67
> docs(operator-docs): Added MergeAll operator documentation

- src/operator-docs/creation/empty.ts
Add initial version of documentation for creation operator 'empty'.
closes ReactiveX/rxjs-docs#76
> docs(operators): add documentation for operator empty

- src/operator-docs/combination/combineLatest.ts
- yarn.lock
Point out that `combineLatest` starts to emit when all sources have emitted at least once and a hint
to `startWith` for a default first value
> docs(combineLatest): Add tip described in issue #143

- src/app/operators/components/operator/operator.component.ts
Selecting operators from left nav was not scrolling back to the top of container making it a little frustrating to browse. This updates the scroll position so you will always start at the top of the documentation for each operator.
On a side note, I think we should also consider adding a default route for the first operator (right now, `combineAll`) if the user navigates to the page without a selection.
> feat(operators): scroll to top of operator container on each route change

- src/operator-docs/utility/do.ts
>  docs(operators): add documentation for operator do

- src/app/operators/operators-routing.module.ts
- src/operator-docs/utility/do.ts
Previously clicking on or navigating to operators section would start at a blank page. This update defaults the route to the first operator in the list if no operator name is supplied.
> feat(operators): default route to first operator when no name supplied

- src/app/operators/components/operator-examples/operator-examples.component.scss
- src/app/operators/components/related-operators/related-operators.component.html
This fixes two small cosmetic issues within the operators page.
1. Hides related operators heading when no related operators exist.
2. Provides some spacing between examples when multiple examples exist.
> fix(operators): hide related operators heading when empty

- src/operator-docs/filtering/distinctUntilChanged.ts
> docs(operators): add documentation for distinctUntilChanged

- src/operator-docs/filtering/take.ts
> docs(operators): add documentation for take

- src/app/app.component.html
- src/app/app.component.ts
- src/app/core/core.module.ts
- src/app/core/services/operator-menu.service.ts
- src/app/operators/operators.component.html
- src/app/operators/operators.component.ts
- src/app/operators/specs/operators.spec.ts
> a11y menu update

- src/operator-docs/filtering/single.ts
> docs(operators): add documentation for single

- src/operator-docs/utility/delay.ts
Add initial version of documentation for utility operator 'delay'
closes #128
> docs(operators): add documentation for operator delay

- src/operator-docs/transformation/buffer.ts
Add initial version of documentation for transformation operator 'buffer'
closes #109
> docs(operators): add documentation for operator buffer

- src/operator-docs/filtering/last.ts
add documentation and an example for the last operator
close #94 
This is my first PR for an open source project, so I'm really looking forward for any kind of feedback. Thank you!
> docs(operators): add documentation for last

- src/operator-docs/transformation/switchMap.ts
> docs (Operator):  add documentation for operator switchMap

- src/operator-docs/creation/from.ts
> docs(operators): add documentation for operator from

- src/operator-docs/combination/pairwise.ts
Closes: https://github.com/ReactiveX/rxjs-docs/issues/68
> docs(operators): add documentation for pairwise

- src/operator-docs/filtering/takeWhile.ts
> docs(operators): add documentation for takeWhile

- src/operator-docs/transformation/mapTo.ts
Add initial version of documentation for transformation operator 'mapTo'
closes [#118](https://github.com/ReactiveX/rxjs-docs/issues/118)
> docs(operators): add documentation for mapTo

- src/operator-docs/transformation/expand.ts
Add initial version of documentation for transformation operator 'expand'
closes #115 
stackblitz: https://stackblitz.com/edit/reactive-expand
> docs(operators): add documentation for expand

- docs_app/src/app/custom-elements/api/api-list.component.html
- docs_app/src/app/custom-elements/api/api-list.component.ts
- On api docs, the filters were specific angular like directive, pipe, etc.,
Now these filters have only rxjs specific options
- Status filter has been disabled until formalize the strategy for code statuses
> feat(docs): Enable only rxjs specific filter options on api docs
