.travis.yml, e2e/app.e2e-spec.ts, e2e/app.po.ts, src/app/app.component.spec.ts, src/app/app.component.ts
=> Travis config

CONTRIBUTING.md, README.md
Add strong recommendation to use the commit script for creating commit messages
https://github.com/ReactiveX/rxjs-docs/issues/19
=> docs(CONTRIBUTING.md, README.md): Instructions regarding commit script

src/operator-docs/filtering/debounce.ts
=> docs: Add documentation for debounce operator

package.json
Updated prettier setting to match TSLint settings.
=> chore(tooling): updated prettier setting to single-quote

.gitignore
Make Git ignore IntelliJ IDEA module (*.iml) files.
=> chore(gitignore): ignore IntelliJ IDEA module files

src/operator-docs/combination/concat.ts
Fixes: https://github.com/ReactiveX/rxjs-docs/issues/63
=> docs(operators): add documentation for concat

src/operator-docs/filtering/filter.ts
=> docs(operators): add documentation for filter

src/operator-docs/filtering/skip.ts
=> docs(operators): add documentation for skip

src/operator-docs/combination/withLatestFrom.ts
Closes: https://github.com/ReactiveX/rxjs-docs/issues/71
=> docs(operators): add documentation for withLatestFrom

src/styles.scss
Slightly darkens app accent color @knittingcodemonkey
=> style(theme): darken application accent color

src/operator-docs/filtering/takeUntil.ts
=> docs(operators): add documentation for takeUntil

src/operator-docs/filtering/throttleTime.ts
=> docs(operators): add documentation for throttleTime

src/operator-docs/filtering/throttle.ts
=> docs(operators): add documentation for throttle

.gitignore, src/app/core/components/toolbar/toolbar.component.html
Add value to menu button to comply with buttons not having readable text. Add package-lock.json to gitignore
no breaking changes
=> fix(a11y): Add value to menu button

src/operator-docs/filtering/sample.ts
=> docs(operators): add documentation for sample

DOCUMENTATION_GUIDELINES.md
Because there currently was no guidelines found in the project, I added a new md file containing
exactly that. This should close issue #247
=> chore(guidelines): Add guidelines on the documentation

src/operator-docs/utility/let.ts
=> docs(operators): add let operator

src/operator-docs/transformation/mergeMap.ts
Add initial version of documentation for transformation operator 'mergeMap'
closes #119
=> docs(operators): add documentation for operator mergeMap

src/app/operators/components/additional-resources/additional-resources.component.html, src/app/operators/components/operator-examples/operator-examples.component.html, src/app/operators/components/operator-parameters/operator-parameters.component.html, src/app/operators/components/operator/operator.component.ts, src/app/operators/components/related-operators/related-operators.component.html, src/app/operators/components/walkthrough/walkthrough.component.html, src/app/operators/operators.module.ts, src/assets/i18n/en.json, src/assets/i18n/ru.json
Add translation for harcode test in operator components
=> feat(i18n): Translate hard code text in operator components

src/app/team/member.component.ts, src/app/team/social-sharing/social-sharing.component.ts, src/app/team/team.component.ts, src/app/team/team.models.ts, src/app/team/team.service.ts
Minor changes to change detection config, model definitions and service internals.
=> refactor: refactor team module

src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/core/components/toolbar/toolbar.component.spec.ts, src/app/core/components/toolbar/toolbar.component.ts, src/app/core/core.module.ts, src/app/core/services/language.service.ts, src/app/core/services/operators.service.spec.ts, src/app/core/services/operators.service.ts, src/app/operators/components/operator/operator.component.ts, src/app/operators/operators-routing.module.ts, src/app/operators/operators.component.ts, src/app/operators/operators.module.ts, src/app/operators/specs/operators.spec.ts, src/i18n/ru/index.ts, src/i18n/ru/utility/delay.ts, src/i18n/ru/utility/do.ts, src/i18n/ru/utility/index.ts, src/operator-docs/index.ts, src/operator-docs/operator.model.ts, src/tsconfig.app.json
Create operators service
Add translation for _do_ operator
Update unit tests
=> feat(i18n): Add a functionality for operators translation

src/operator-docs/creation/timer.ts
Add docs for operator : creation - timer #84
=> docs(observables): Add docs for operator : creation - timer
